
[hyperparameters]
epochs=25
batch_size=10

[umap_params]
n_components=5

[cluster_params]


[vectorizer_params]
stop_words="english"
decay=0.01

[tfidf_params]
reduce_frequent_words=true
bm25_weighting=true
