
[hyperparameters]
epochs=1
batch_size=1000

[umap_params]
n_components=5

[cluster_params]
clustering_threshold=1.0
fading_factor = 0.01
cleanup_interval=2.0
intersection_factor = 0.3
minimum_weight = 1.0

[vectorizer_params]
stop_words="english"
decay=0.01

[tfidf_params]
reduce_frequent_words=true
bm25_weighting=true
