# CLMS Capstone | Dean Cahill 
# Clustering Algorithm --- Config File

num_epochs = 50

[af_params]
damping = 0.5
max_iter = 200 
convergence_iter = 15
copy = true
affinity = "euclidean"
verbose = false 
random_state = 0


